AWSTemplateFormatVersion: '2010-09-09'
Description: 'Nested Stack for Amazon Verified Permissions (AVP) resources'

Parameters:
  CognitoUserPoolArn:
    Type: String
    Description: 'ARN of the Cognito User Pool'
  CognitoClientId:
    Type: String
    Description: 'Cognito User Pool Client ID'
  CognitoUserPoolId:
    Type: String
    Description: 'Cognito User Pool ID'

Resources:
  MyPolicyStore:
    Type: AWS::VerifiedPermissions::PolicyStore
    Properties:
      Description: "Policy store for the Recube::MyApp application"
      ValidationSettings:
        Mode: STRICT
      Schema:
        CedarJson: !Sub |
            {
              "Recube::MyApp": {
                "entityTypes": {
                  "User": { "memberOfTypes": ["Roles"] },
                  "Roles": {},
                  "Bike": {},
                  "Car": {}
                },
                "actions": {
                  "get /bikes": {
                    "appliesTo": { "principalTypes": ["User","Roles"], "resourceTypes": ["Bike"] }
                  },
                  "post /bikes": {
                    "appliesTo": { "principalTypes": ["User","Roles"], "resourceTypes": ["Bike"] }
                  },
                  "get /cars": {
                    "appliesTo": { "principalTypes": ["User","Roles"], "resourceTypes": ["Car"] }
                  },
                  "post /cars": {
                    "appliesTo": { "principalTypes": ["User","Roles"], "resourceTypes": ["Car"] }
                  },
                  "get /bike/{bikeId}": {
                    "appliesTo": { "principalTypes": ["User","Roles"], "resourceTypes": ["Bike"] }
                  },
                  "put /bike/{bikeId}": {
                    "appliesTo": { "principalTypes": ["User","Roles"], "resourceTypes": ["Bike"] }
                  },
                  "delete /bike/{bikeId}": {
                    "appliesTo": { "principalTypes": ["User","Roles"], "resourceTypes": ["Bike"] }
                  },
                  "get /car/{carId}": {
                    "appliesTo": { "principalTypes": ["User","Roles"], "resourceTypes": ["Car"] }
                  },
                  "put /car/{carId}": {
                    "appliesTo": { "principalTypes": ["User","Roles"], "resourceTypes": ["Car"] }
                  },
                  "delete /car/{carId}": {
                    "appliesTo": { "principalTypes": ["User","Roles"], "resourceTypes": ["Car"] }
                  }
                }
              }
            }
  
  ViewersPolicy:
    Type: AWS::VerifiedPermissions::Policy
    Properties:
      PolicyStoreId: !Ref MyPolicyStore
      Definition:
        Static:
          Description: "Allow Viewers to getBike and getCars"
          Statement: !Sub |
            permit (
                principal in Recube::MyApp::Roles::"${CognitoUserPoolId}|viewers",
                action in [
                    Recube::MyApp::Action::"get /bikes",
                    Recube::MyApp::Action::"get /bike/{bikeId}",
                    Recube::MyApp::Action::"get /cars",
                    Recube::MyApp::Action::"get /car/{carId}"
                ],
                resource
            );

  AdminsPolicy:
    Type: AWS::VerifiedPermissions::Policy
    Properties:
      PolicyStoreId: !Ref MyPolicyStore
      Definition:
        Static:
          Description: "Allow Admins to perform all actions"
          Statement: !Sub |
            permit (
                principal in Recube::MyApp::Roles::"${CognitoUserPoolId}|admins",
                action,
                resource
            );

  IdentitySource:
    Type: AWS::VerifiedPermissions::IdentitySource
    Properties:
      PolicyStoreId: !Ref MyPolicyStore
      Configuration:
        CognitoUserPoolConfiguration:
          UserPoolArn: !Ref CognitoUserPoolArn
          ClientIds:
            - !Ref CognitoClientId
          GroupConfiguration:
            GroupEntityType: "Recube::MyApp::Roles"
      PrincipalEntityType: "Recube::MyApp::User"

Outputs:
  PolicyStoreId:
    Description: "The ID of the AVP Policy Store"
    Value: !GetAtt MyPolicyStore.PolicyStoreId
  PolicyStoreArn:
    Description: "The ARN of the AVP Policy Store"
    Value: !GetAtt MyPolicyStore.Arn